#!/usr/bin/env python3
"""Generate a complete null UI (src/ui/nop/uinop_game.c) from ui.h declarations.
The headless server links this so game_turn_process runs with no real UI: displays
are no-ops and decisions auto-resolve."""
import re

UI_H = "src/ui.h"
OUT = "src/ui/nop/uinop_game.c"

# already defined in uinop.c
SKIP = {"ui_early_init", "ui_init", "ui_shutdown"}

# functions whose non-void return needs a specific default (else "0")
RET = {
    "ui_battle_init": "UI_BATTLE_AUTORESOLVE_AUTO",   # auto-resolve every battle
    "ui_battle_turn": "UI_BATTLE_ACT_AUTO",
    "ui_battle_ai_post": "false",
    "ui_game_turn": "UI_TURN_ACT_NEXT_TURN",
    "ui_main_menu": "MAIN_MENU_ACT_QUIT_GAME",
    "ui_explore": "false",       # don't auto-colonize
    "ui_bomb_ask": "false",      # don't auto-bomb
    "ui_election_accept": "false",
}
# functions needing a full custom body
CUSTOM = {
    "ui_get_strbuf": "{\n    static char buf[1024];\n    return buf;\n}",
    "ui_spy_sabotage_ask": "{\n    (void)g; (void)spy; (void)target;\n    if (planetptr) { *planetptr = PLANET_NONE; }\n    return 0;\n}",
}

decl_re = re.compile(r'^extern\s+(.*?\b(ui_[a-z0-9_]+))\s*\((.*)\)\s*;\s*$')

src = open(UI_H).read()
lines = []
for line in src.splitlines():
    m = decl_re.match(line.strip())
    if not m:
        continue
    ret_and_name, name, params = m.group(1), m.group(2), m.group(3).strip()
    if name in SKIP:
        continue
    rettype = ret_and_name[:ret_and_name.rfind(name)].strip()
    sig = f"{rettype} {name}({params})"
    if name in CUSTOM:
        lines.append(sig + "\n" + CUSTOM[name] + "\n")
        continue
    if rettype == "void":
        body = "{\n}"
    else:
        val = RET.get(name, "0")
        body = "{\n    return " + val + ";\n}"
    lines.append(sig + "\n" + body + "\n")

with open(OUT, "w") as f:
    f.write("/* 1oom-mp: complete null UI for the headless server (auto-generated by\n")
    f.write("   gen_nullui.py from ui.h). Displays are no-ops; decisions auto-resolve so\n")
    f.write("   game_turn_process runs without a real UI. */\n")
    f.write('#include "config.h"\n')
    f.write('#include "ui.h"\n')
    f.write('#include "types.h"\n')
    f.write('#include "game_planet.h"\n\n')
    f.write("bool ui_use_audio = false;\n\n")
    f.write("\n".join(lines))
    f.write("\n")
print(f"generated {OUT}: {len(lines)} stubs")
