/* 1oom-mp: complete null UI for the headless server (auto-generated by
   gen_nullui.py from ui.h). Displays are no-ops; decisions auto-resolve so
   game_turn_process runs without a real UI. */
#include "config.h"
#include "ui.h"
#include "types.h"
#include "game.h"
#include "game_planet.h"
#include "game_audience.h"
#include "game_battle.h"
#include "game_election.h"
#include "game_ground.h"
#include "game_turn.h"
#include "mp.h"
#include <stdio.h>
#include <string.h>

bool ui_use_audio = false;

void ui_early_show_message_box(const char *msg)
{
}

int ui_late_init(void)
{
    return 0;
}

char * ui_get_strbuf(void)
{
    static char buf[1024];
    return buf;
}

void ui_play_intro(void)
{
}

void ui_play_ending_good(int race, const char *name)
{
}

void ui_play_ending_tyrant(int race, const char *name)
{
}

void ui_play_ending_funeral(int banner_live, int banner_dead)
{
}

void ui_play_ending_exile(const char *name)
{
}

main_menu_action_t ui_main_menu(struct game_new_options_s *newopts, struct game_new_options_s *customopts, struct game_new_options_s *challengeopts, int *load_game_i_ptr)
{
    return MAIN_MENU_ACT_QUIT_GAME;
}

void ui_game_start(struct game_s *g)
{
}

void ui_game_end(struct game_s *g)
{
}

void ui_sound_play_sfx(int sfxi)
{
}

ui_turn_action_t ui_game_turn(struct game_s *g, int *load_game_i_ptr, int pi)
{
    return UI_TURN_ACT_NEXT_TURN;
}

void * ui_gmap_basic_init(struct game_s *g, bool show_player_switch)
{
    /* 1oom-mp: the headless server has no animation, but this is the exact moment
       fleet movement begins — let the MP server snapshot the pre-movement state
       here so it can stream it to clients to animate. */
    if (game_mp_premove_hook) { game_mp_premove_hook(g); }
    return 0;
}

void ui_gmap_basic_start_player(void *ctx, int pi)
{
}

void ui_gmap_basic_start_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_draw_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_finish_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_shutdown(void *ctx)
{
}

uint8_t * ui_gfx_get_ship(int look)
{
    return 0;
}

uint8_t * ui_gfx_get_planet(int look)
{
    return 0;
}

uint8_t * ui_gfx_get_rock(int look)
{
    return 0;
}

ui_battle_autoresolve_t ui_battle_init(struct battle_s *bt)
{
    /* 1oom-mp: init EVERY human side's client IN PARALLEL (each runs the autoresolve
       prompt + sets up its battle UI at the same time). Battle goes interactive if any
       human picks Continue. Default AUTO outside MP. */
    if (g_mp_decision_hook_multi) {
        int players[2];
        int n = 0;
        for (int side = SIDE_L; side <= SIDE_R; ++side) {
            if (bt->s[side].flag_human) { players[n++] = bt->s[side].party; }
        }
        if (n > 0) {
            uint8_t modes[2] = { UI_BATTLE_AUTORESOLVE_AUTO, UI_BATTLE_AUTORESOLVE_AUTO };
            if (g_mp_decision_hook_multi(players, n, MP_DEC_BATTLE_INIT, bt, (int)sizeof(*bt), modes, 1) == 0) {
                ui_battle_autoresolve_t result = UI_BATTLE_AUTORESOLVE_AUTO;
                for (int i = 0; i < n; ++i) {
                    if (modes[i] == UI_BATTLE_AUTORESOLVE_OFF) { result = UI_BATTLE_AUTORESOLVE_OFF; }
                }
                return result;
            }
        }
    }
    return UI_BATTLE_AUTORESOLVE_AUTO;
}

void ui_battle_shutdown(struct battle_s *bt, bool colony_destroyed, int winner)
{
    /* 1oom-mp: tear down EVERY human side's battle UI -- must mirror ui_battle_init, which inits
       all human sides. If only one side were told to end (the old SIDE_L-or-SIDE_R pick), a human
       on the OTHER side of a human-vs-human battle would keep its battle context (s_mp_battle_uictx)
       set forever, and then re-render that stale battle on every later combat-wait broadcast --
       even while completely uninvolved in someone else's fight. */
    if (g_mp_decision_hook_multi) {
        int players[2];
        int n = 0;
        for (int side = SIDE_L; side <= SIDE_R; ++side) {
            if (bt->s[side].flag_human) { players[n++] = bt->s[side].party; }
        }
        if (n > 0) {
            static uint8_t buf[sizeof(struct battle_s) + 8];
            int32_t w = winner; uint8_t resp[2] = { 0, 0 };
            memcpy(buf, bt, sizeof(struct battle_s));
            buf[sizeof(struct battle_s)] = colony_destroyed ? 1 : 0;
            memcpy(buf + sizeof(struct battle_s) + 1, &w, 4);
            g_mp_decision_hook_multi(players, n, MP_DEC_BATTLE_END, buf, (int)sizeof(struct battle_s) + 5, resp, 1);
        }
    }
}

static void mp_spec_send(const struct battle_s *bt, uint8_t kind, const int *args, int nargs); /* fwd: defined below */

void ui_battle_draw_misshield(const struct battle_s *bt, int target_i, int target_x, int target_y, int missile_i)
{
}

void ui_battle_draw_damage(const struct battle_s *bt, int target_i, int target_x, int target_y, uint32_t damage)
{
    int a[5] = { target_i, target_x, target_y, (int)(damage & 0xffff), (int)((damage >> 16) & 0xffff) };
    mp_spec_send(bt, UI_MP_SPEC_DAMAGE, a, 5);
}

void ui_battle_draw_explos_small(const struct battle_s *bt, int x, int y)
{
}

void ui_battle_draw_basic(const struct battle_s *bt)
{
    /* 1oom-mp: stream the battle to any human NOT currently acting, so they can watch
       the fight progress instead of staring at a frozen frame. */
    if (g_mp_spectate_hook) {
        battle_side_i_t cside = bt->item[bt->cur_item].side;
        int actor = ((cside == SIDE_L) || (cside == SIDE_R)) ? bt->s[cside].party : -1;
        for (int side = SIDE_L; side <= SIDE_R; ++side) {
            if (bt->s[side].flag_human && (bt->s[side].party != actor)) {
                g_mp_spectate_hook(bt->s[side].party, bt, (int)sizeof(*bt));
            }
        }
    }
}

void ui_battle_draw_basic_copy(const struct battle_s *bt)
{
}

void ui_battle_draw_missile(const struct battle_s *bt, int missilei, int x, int y, int tx, int ty)
{
}

void ui_battle_draw_cloaking(const struct battle_s *bt, int from, int to, int sx, int sy)
{
}

void ui_battle_draw_arena(const struct battle_s *bt, int itemi, int dmode)
{
}

void ui_battle_draw_item(const struct battle_s *bt, int itemi, int x, int y)
{
}

/* 1oom-mp: push a small battle animation event to the human(s) NOT currently acting (same audience
   as the draw_basic snapshot) so a spectator sees the attack play out. args are sent as int16. */
static void mp_spec_send(const struct battle_s *bt, uint8_t kind, const int *args, int nargs)
{
    if (!g_mp_spectate_hook) { return; }
    uint8_t b[1 + 2 * 8];
    if (nargs > 8) { nargs = 8; }
    b[0] = kind;
    for (int i = 0; i < nargs; ++i) { b[1 + i * 2] = (uint8_t)(args[i] & 0xff); b[2 + i * 2] = (uint8_t)((args[i] >> 8) & 0xff); }
    {
        /* send to EVERY human in the battle, including the one acting — they should see their own
           shot/retreat fire (the actor only gets state snapshots at its decision points otherwise). */
        for (battle_side_i_t side = SIDE_L; side <= SIDE_R; ++side) {
            if (bt->s[side].flag_human) {
                g_mp_spectate_hook(bt->s[side].party, b, 1 + nargs * 2);
            }
        }
    }
}

void ui_battle_draw_bomb_attack(const struct battle_s *bt, int attacker_i, int target_i, ui_battle_bomb_t bombtype)
{
    int a[3] = { attacker_i, target_i, (int)bombtype };
    mp_spec_send(bt, UI_MP_SPEC_BOMB, a, 3);
}

void ui_battle_draw_beam_attack(const struct battle_s *bt, int attacker_i, int target_i, int wpni)
{
    int a[3] = { attacker_i, target_i, wpni };
    mp_spec_send(bt, UI_MP_SPEC_BEAM, a, 3);
}

void ui_battle_draw_stasis(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STASIS, a, 2);
}

void ui_battle_draw_pulsar(const struct battle_s *bt, int attacker_i, int ptype, const uint32_t *dmgtbl)
{
}

void ui_battle_draw_stream1(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STREAM1, a, 2);
}

void ui_battle_draw_stream2(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STREAM2, a, 2);
}

void ui_battle_draw_blackhole(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_BLACKHOLE, a, 2);
}

void ui_battle_draw_technull(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_TECHNULL, a, 2);
}

void ui_battle_draw_repulse(const struct battle_s *bt, int attacker_i, int target_i, int sx, int sy)
{
    int a[4] = { attacker_i, target_i, sx, sy };
    mp_spec_send(bt, UI_MP_SPEC_REPULSE, a, 4);
}

void ui_battle_draw_retreat(const struct battle_s *bt)
{
    int a[1] = { bt->cur_item };
    mp_spec_send(bt, UI_MP_SPEC_RETREAT, a, 1);
}

void ui_battle_draw_bottom(const struct battle_s *bt)
{
}

void ui_battle_draw_planetinfo(const struct battle_s *bt, bool side_r)
{
}

void ui_battle_draw_scan(const struct battle_s *bt, bool side_r)
{
}

void ui_battle_draw_finish(const struct battle_s *bt)
{
}

void ui_battle_area_setup(const struct battle_s *bt)
{
}

void ui_battle_turn_pre(const struct battle_s *bt)
{
}

void ui_battle_turn_post(const struct battle_s *bt)
{
}

ui_battle_action_t ui_battle_turn(const struct battle_s *bt)
{
    /* 1oom-mp: ask the current ship's owner for one action (client runs the local
       poll loop and returns a real action; the server's per-frame loop becomes
       one RPC per action). Default AUTO. */
    if (g_mp_decision_hook) {
        battle_side_i_t side = bt->item[bt->cur_item].side;
        int party = ((side == SIDE_L) || (side == SIDE_R)) ? bt->s[side].party : -1;
        if (party >= 0) {
            uint8_t act = UI_BATTLE_ACT_AUTO;
            int r = g_mp_decision_hook(party, MP_DEC_BATTLE_TURN, bt, (int)sizeof(*bt), &act, 1);
            if (r >= 1) { return act; }
        }
    }
    return UI_BATTLE_ACT_AUTO;
}

void ui_battle_ai_pre(const struct battle_s *bt)
{
}

bool ui_battle_ai_post(const struct battle_s *bt)
{
    return false;
}

int ui_spy_steal(struct game_s *g, int spy, int target, uint8_t flags_field)
{
    /* 1oom-mp: ask the spying human which tech field to steal (default 0 outside MP) */
    if (g_mp_decision_hook) {
        struct { int32_t spy, target; uint8_t flags; } rq;
        int32_t fld = 0;
        rq.spy = spy; rq.target = target; rq.flags = flags_field;
        int r = g_mp_decision_hook(spy, MP_DEC_SPY_STEAL, &rq, sizeof(rq), &fld, sizeof(fld));
        if (r >= (int)sizeof(fld)) { return fld; }
    }
    return 0;
}

void ui_spy_stolen(struct game_s *g, int pi, int spy, int field, uint8_t tech)
{
}

ui_sabotage_t ui_spy_sabotage_ask(struct game_s *g, int spy, int target, planet_id_t *planetptr)
{
    /* 1oom-mp: ask the spying human what to sabotage + where (default none outside MP) */
    if (g_mp_decision_hook) {
        struct { int32_t spy, target; } rq;
        struct { int32_t act; uint16_t planet; } rs = { 0, PLANET_NONE };
        rq.spy = spy; rq.target = target;
        int r = g_mp_decision_hook(spy, MP_DEC_SPY_SABOTAGE, &rq, sizeof(rq), &rs, sizeof(rs));
        if (r >= (int)sizeof(rs)) {
            if (planetptr) { *planetptr = (planet_id_t)rs.planet; }
            return (ui_sabotage_t)rs.act;
        }
    }
    if (planetptr) { *planetptr = PLANET_NONE; }
    return 0;
}

int ui_spy_sabotage_done(struct game_s *g, int pi, int spy, int target, ui_sabotage_t act, int other1, int other2, planet_id_t planet, int snum)
{
    return 0;
}

void ui_newtech(struct game_s *g, int pi)
{
}

bool ui_explore(struct game_s *g, int pi, planet_id_t planet_i, bool by_scanner, bool flag_colony_ship)
{
    /* 1oom-mp: the server never auto-colonizes a human's colony ship — the ship waits
       in orbit and the human is asked on their own client at turn start (see
       ui_mp_colonize_incoming), which records a colonize order the server applies. */
    return false;
}

void ui_landing(struct game_s *g, int pi, planet_id_t planet_i)
{
}

bool ui_bomb_ask(struct game_s *g, int pi, planet_id_t planet_i, int pop_inbound)
{
    /* 1oom-mp: ask the attacking human's client whether to bomb (the server blocks
       on the answer). Default "no" outside MP (g_mp_decision_hook NULL). */
    if (g_mp_decision_hook) {
        uint8_t req[8], resp = 0;
        req[0] = (uint8_t)(pi >> 8);          req[1] = (uint8_t)pi;
        req[2] = (uint8_t)(planet_i >> 8);    req[3] = (uint8_t)planet_i;
        req[4] = (uint8_t)(pop_inbound >> 24); req[5] = (uint8_t)(pop_inbound >> 16);
        req[6] = (uint8_t)(pop_inbound >> 8);  req[7] = (uint8_t)pop_inbound;
        int r = g_mp_decision_hook(pi, MP_DEC_BOMB, req, 8, &resp, 1);
        return (r >= 1) && (resp != 0);
    }
    return false;
}

void ui_bomb_show(struct game_s *g, int pi, int attacker_i, int owner_i, planet_id_t planet_i, int popdmg, int factdmg, bool play_music, bool hide_other)
{
    /* 1oom-mp: the server resolves the bombing on this null UI, so relay the result (pop killed /
       factories destroyed) to the human attacker AND the human owner, who each render it. */
    (void)pi;
    if (g_mp_decision_hook_multi) {
        int players[2], n = 0;
        int cand[2]; cand[0] = attacker_i; cand[1] = owner_i;
        for (int k = 0; k < 2; ++k) {
            int p = cand[k];
            if ((p < 0) || (p >= (int)g->players) || !IS_HUMAN(g, p)) { continue; }
            bool dup = false;
            for (int j = 0; j < n; ++j) { if (players[j] == p) { dup = true; break; } }
            if (!dup) { players[n++] = p; }
        }
        if (n > 0) {
            uint8_t req[16], resp[2] = {0, 0};
            int q = 0;
            req[q++] = (uint8_t)(attacker_i >> 8); req[q++] = (uint8_t)attacker_i;
            req[q++] = (uint8_t)(owner_i >> 8);    req[q++] = (uint8_t)owner_i;
            req[q++] = (uint8_t)(planet_i >> 8);   req[q++] = (uint8_t)planet_i;
            req[q++] = (uint8_t)(popdmg >> 24); req[q++] = (uint8_t)(popdmg >> 16); req[q++] = (uint8_t)(popdmg >> 8); req[q++] = (uint8_t)popdmg;
            req[q++] = (uint8_t)(factdmg >> 24); req[q++] = (uint8_t)(factdmg >> 16); req[q++] = (uint8_t)(factdmg >> 8); req[q++] = (uint8_t)factdmg;
            req[q++] = play_music ? 1 : 0;
            req[q++] = hide_other ? 1 : 0;
            g_mp_decision_hook_multi(players, n, MP_DEC_BOMB_SHOW, req, q, resp, 1);
        }
    }
}

void ui_turn_pre(const struct game_s *g)
{
}

void ui_turn_msg(struct game_s *g, int pi, const char *str)
{
}

void ui_ground(struct game_s *g, struct ground_s *gr)
{
    /* 1oom-mp: the server resolves the invasion on this null UI, so relay the result + animation to
       the human attacker AND the human defender so both watch it (ground_s is pointer-free). */
    if (g_mp_decision_hook_multi) {
        int players[2], n = 0;
        for (int side = 0; side < 2; ++side) {
            int p = gr->s[side].player;
            if ((p < 0) || (p >= (int)g->players) || !IS_HUMAN(g, p)) { continue; }
            bool dup = false;
            for (int j = 0; j < n; ++j) { if (players[j] == p) { dup = true; break; } }
            if (!dup) { players[n++] = p; }
        }
        if (n > 0) {
            uint8_t resp[2] = {0, 0};
            g_mp_decision_hook_multi(players, n, MP_DEC_GROUND, gr, (int)sizeof(*gr), resp, 1);
        }
    }
}

void ui_news_start(void)
{
}

void ui_news(struct game_s *g, struct news_s *ns)
{
}

void ui_news_end(void)
{
}

/* 1oom-mp: the council is a plenary event (every empire is present), so stream the chamber state to
   ALL human players via the spectate channel -- they render it while waiting (shared synchronous
   view). The vote/accept stay per-human (decision RPC). Pointers are zeroed for transport. */
static void mp_election_relay(struct election_s *el, int kind)
{
    if (!g_mp_spectate_hook || !el || !el->g) { return; }
    uint8_t buf[1 + sizeof(struct election_s)];
    int len = 1;
    buf[0] = (uint8_t)kind;
    if (kind == UI_MP_SPEC_COUNCIL) {
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        memcpy(buf + 1, &e, sizeof(e));
        len = 1 + (int)sizeof(e);
    }
    for (player_id_t p = PLAYER_0; p < el->g->players; ++p) {
        if (IS_HUMAN(el->g, p)) { g_mp_spectate_hook(p, buf, len); }
    }
}

void ui_election_start(struct election_s *el)
{
    mp_election_relay(el, UI_MP_SPEC_COUNCIL);
}

void ui_election_show(struct election_s *el)
{
    mp_election_relay(el, UI_MP_SPEC_COUNCIL);
}

void ui_election_delay(struct election_s *el, int delay)
{
}

/* 1oom-mp: the galactic-council vote + accept happen during resolution; ship the
   election state to the voting human's client and ask there (the struct's pointers
   are zeroed for transport and re-pointed client-side). Default outside MP unchanged. */
int ui_election_vote(struct election_s *el, int player_i)
{
    if (g_mp_decision_hook) {
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        uint8_t req[sizeof(struct election_s) + 4];
        int32_t pi32 = player_i, vote = 0;
        memcpy(req, &e, sizeof(e));
        memcpy(req + sizeof(e), &pi32, 4);
        int r = g_mp_decision_hook(player_i, MP_DEC_ELECTION_VOTE, req, (int)sizeof(req), &vote, sizeof(vote));
        if (r >= (int)sizeof(vote)) { return vote; }
    }
    return 0;
}

bool ui_election_accept(struct election_s *el, int player_i)
{
    if (g_mp_decision_hook) {
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        uint8_t req[sizeof(struct election_s) + 4], resp = 0;
        int32_t pi32 = player_i;
        memcpy(req, &e, sizeof(e));
        memcpy(req + sizeof(e), &pi32, 4);
        int r = g_mp_decision_hook(player_i, MP_DEC_ELECTION_ACCEPT, req, (int)sizeof(req), &resp, 1);
        if (r >= 1) { return resp != 0; }
    }
    return false;
}

void ui_election_end(struct election_s *el)
{
    mp_election_relay(el, UI_MP_SPEC_COUNCIL_END);
}

void ui_election_ctx_load(struct election_s *el)
{
}

void ui_election_ctx_free(struct election_s *el)
{
}

void ui_election_spectate(struct election_s *el)
{
}

/* 1oom-mp: the AI's diplomacy with a human runs through game_audience on this headless server;
   relay each ui_audience_* call to the human's client (au->ph) so they actually see the audience
   and answer. If au->ph isn't a connected human, the decision hook returns <0 and we fall back to
   the old auto-resolve default (0). Strings are sent as text since they may point at static
   game-string tables or the inline diplo_msg/strtbl_buf. */
static int16_t mp_audience_relay(uint8_t subtype, uint8_t ntpi, struct audience_s *au)
{
    if (!g_mp_decision_hook) { return 0; }
    static uint8_t req[8192];
    int pos = 0;
    req[pos++] = subtype;
    req[pos++] = ntpi;
    memcpy(req + pos, au, sizeof(*au)); pos += (int)sizeof(*au);
    uint16_t blen = au->buf ? (uint16_t)strlen(au->buf) : 0;
    if (blen > AUDIENCE_DIPLO_MSG_SIZE) { blen = AUDIENCE_DIPLO_MSG_SIZE; }
    memcpy(req + pos, &blen, 2); pos += 2;
    if (blen) { memcpy(req + pos, au->buf, blen); pos += blen; }
    uint8_t nstr = 0;
    while ((nstr < AUDIENCE_STR_MAX) && au->strtbl[nstr]) { ++nstr; }
    req[pos++] = nstr;
    for (int i = 0; i < nstr; ++i) {
        uint16_t l = (uint16_t)strlen(au->strtbl[i]);
        if (l > 255) { l = 255; }
        memcpy(req + pos, &l, 2); pos += 2;
        memcpy(req + pos, au->strtbl[i], l); pos += l;
    }
    req[pos++] = au->condtbl ? 1 : 0;
    if (au->condtbl) { for (int i = 0; i < nstr; ++i) { req[pos++] = au->condtbl[i] ? 1 : 0; } }
    uint8_t rsp[4];
    int r = g_mp_decision_hook(au->ph, MP_DEC_AUDIENCE, req, pos, rsp, (int)sizeof(rsp));
    if (r >= 2) { int16_t v; memcpy(&v, rsp, 2); return v; }
    return 0;
}

void ui_audience_start(struct audience_s *au) { mp_audience_relay(MP_AUD_START, 0, au); }
void ui_audience_show1(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW1, 0, au); }
void ui_audience_show2(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW2, 0, au); }
void ui_audience_show3(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW3, 0, au); }
int16_t ui_audience_ask2a(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK2A, 0, au); }
int16_t ui_audience_ask2b(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK2B, 0, au); }
int16_t ui_audience_ask3(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK3, 0, au); }
int16_t ui_audience_ask4(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK4, 0, au); }
void ui_audience_newtech(struct audience_s *au, int pi) { mp_audience_relay(MP_AUD_NEWTECH, (uint8_t)pi, au); }
void ui_audience_end(struct audience_s *au) { mp_audience_relay(MP_AUD_END, 0, au); }

void ui_newships(struct game_s *g, int pi)
{
}

void ui_copyprotection_check(struct game_s *g)
{
}

void ui_copyprotection_lose(struct game_s *g, struct game_end_s *ge)
{
}

void ui_mp_wait(int reason)
{
    (void)reason; /* headless server: never called (server side doesn't wait on a UI) */
}

void ui_mp_battle_spectate(const struct battle_s *bt)
{
    (void)bt; /* headless: client-only */
}

void ui_mp_battle_glide(struct battle_s *bt, int itemi, int sx, int sy)
{
    (void)bt; (void)itemi; (void)sx; (void)sy; /* headless: client-only */
}

int ui_mp_lobby_run(int my_id)
{
    (void)my_id;
    return 0; /* headless server: never runs a client lobby (uses setup_game directly) */
}

