/* 1oom-mp: complete null UI for the headless server (auto-generated by
   gen_nullui.py from ui.h). Displays are no-ops; decisions auto-resolve so
   game_turn_process runs without a real UI. */
#include "config.h"
#include "ui.h"
#include "types.h"
#include "game.h"
#include "lib.h"
#include "game_planet.h"
#include "game_audience.h"
#include "game_battle.h"
#include "game_election.h"
#include "game_ground.h"
#include "game_turn.h"
#include "game_news.h"
#include "mp.h"
#include "log.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>

bool ui_use_audio = false;

void ui_early_show_message_box(const char *msg)
{
}

int ui_late_init(void)
{
    return 0;
}

char * ui_get_strbuf(void)
{
    static char buf[1024];
    return buf;
}

void ui_play_intro(void)
{
}

void ui_play_ending_good(int race, const char *name)
{
}

void ui_play_ending_tyrant(int race, const char *name)
{
}

void ui_play_ending_funeral(int banner_live, int banner_dead)
{
}

void ui_play_ending_exile(const char *name)
{
}

main_menu_action_t ui_main_menu(struct game_new_options_s *newopts, struct game_new_options_s *customopts, struct game_new_options_s *challengeopts, int *load_game_i_ptr)
{
    return MAIN_MENU_ACT_QUIT_GAME;
}

void ui_game_start(struct game_s *g)
{
}

void ui_game_end(struct game_s *g)
{
}

void ui_sound_play_sfx(int sfxi)
{
}

ui_turn_action_t ui_game_turn(struct game_s *g, int *load_game_i_ptr, int pi)
{
    return UI_TURN_ACT_NEXT_TURN;
}

void * ui_gmap_basic_init(struct game_s *g, bool show_player_switch)
{
    /* 1oom-mp: the headless server has no animation, but this is the exact moment
       fleet movement begins — let the MP server snapshot the pre-movement state
       here so it can stream it to clients to animate. */
    if (game_mp_premove_hook) { game_mp_premove_hook(g); }
    return 0;
}

void ui_gmap_basic_start_player(void *ctx, int pi)
{
}

void ui_gmap_basic_start_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_draw_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_finish_frame(void *ctx, int pi)
{
}

void ui_gmap_basic_shutdown(void *ctx)
{
}

uint8_t * ui_gfx_get_ship(int look)
{
    return 0;
}

uint8_t * ui_gfx_get_planet(int look)
{
    return 0;
}

uint8_t * ui_gfx_get_rock(int look)
{
    return 0;
}

/* 1oom-mp: each side's ship stacks captured at battle start, diffed at shutdown into per-design
   losses for the end-of-turn combat report. One battle resolves at a time, so one static suffices. */
struct mp_shipsnap_s { uint8_t side, look, hull; uint16_t num; };
static struct mp_shipsnap_s s_battle_snap[BATTLE_ITEM_MAX];
static int s_battle_snap_n = 0;
static uint16_t s_battle_snap_bases = 0; /* defending planet's missile bases at battle start */
static int s_battle_snap_pside = -1;     /* which side the planet (its bases) is on */

static uint16_t mp_battle_item_num(const struct battle_s *bt, int side, int look, int hull)
{
    uint16_t total = 0;
    for (int i = 1; (i <= (int)bt->items_num) && (i < BATTLE_ITEM_MAX); ++i) {
        const struct battle_item_s *it = &bt->item[i];
        if (((int)it->side == side) && ((int)it->look == look) && ((int)it->hull == hull)) { total += it->num; }
    }
    return total;
}

/* 1oom-mp: stream a battle event to teammates of either combatant (observers); defined below.
   Returns the number of observer clients it sent to (0 if nobody qualifies / hook is off). */
static int mp_spec_send_observers(const struct battle_s *bt, const void *data, int len, int reliable);

/* 1oom-mp teams: per-owner battle control. The combatants are every HUMAN empire on either side (a
   side's lead + its joined allied teammates); EACH drives its OWN ships, while non-owner teammates
   only observe. s_battle_owner_mode[p] is each owner's autoresolve choice (OFF=fight live, else flee). */
static uint8_t s_battle_owner_mode[PLAYER_NUM];
static int mp_battle_human_owners(const struct battle_s *bt, int *players, battle_side_i_t *sides) {
    int n = 0;
    for (battle_side_i_t side = SIDE_L; side <= SIDE_R; ++side) {
        for (int k = 0; k < (int)bt->s[side].num_parties; ++k) {
            int p = bt->s[side].parties[k], j;
            bool dup = false;
            if ((p < 0) || (p >= PLAYER_NUM) || !IS_HUMAN(bt->g, p)) { continue; }
            for (j = 0; j < n; ++j) { if (players[j] == p) { dup = true; break; } }
            if (dup) { continue; }
            players[n] = p; if (sides) { sides[n] = side; } ++n;
            if (n >= 2 * BATTLE_SIDE_PARTIES_MAX) { return n; }
        }
    }
    return n;
}
static bool mp_battle_is_owner(const struct battle_s *bt, int p) {
    for (battle_side_i_t side = SIDE_L; side <= SIDE_R; ++side) {
        for (int k = 0; k < (int)bt->s[side].num_parties; ++k) { if (bt->s[side].parties[k] == p) { return true; } }
    }
    return false;
}
/* 1oom-mp: count the human teammates who would be OFFERED the "press W to watch" prompt for this
   battle -- i.e. a human on a lead's team who is NOT a combatant. Mirrors the filter in
   mp_spec_send_observers exactly; used only for the diagnostic log line at the spectate gate so a
   "the watch prompt never appeared" report can be told apart from "no eligible observers". */
static int mp_battle_observer_count(const struct battle_s *bt) {
    const struct game_s *g = bt->g;
    int pl, pr, n = 0;
    if (!g) { return 0; }
    pl = bt->s[SIDE_L].party; pr = bt->s[SIDE_R].party;
    for (int p = 0; p < g->players; ++p) {
        if ((p == pl) || (p == pr) || !IS_HUMAN(g, p) || mp_battle_is_owner(bt, p)) { continue; }
        if (((pl >= 0) && (g->mp_team[pl] != 0) && (g->mp_team[p] == g->mp_team[pl]))
         || ((pr >= 0) && (g->mp_team[pr] != 0) && (g->mp_team[p] == g->mp_team[pr]))) { ++n; }
    }
    return n;
}
/* send a battle frame to every human OWNER (combatant), optionally skipping one (the current actor). */
static void mp_spec_send_owners(const struct battle_s *bt, const void *data, int len, int reliable, int except) {
    int players[2 * BATTLE_SIDE_PARTIES_MAX]; int n, i;
    if (!g_mp_spectate_hook) { return; }
    n = mp_battle_human_owners(bt, players, NULL);
    for (i = 0; i < n; ++i) { if (players[i] != except) { g_mp_spectate_hook(players[i], data, len, reliable); } }
}

ui_battle_autoresolve_t ui_battle_init(struct battle_s *bt)
{
    /* snapshot the initial ship stacks (item[0] is the planet, so start at 1) for the loss diff */
    s_battle_snap_n = 0;
    for (int i = 1; (i <= (int)bt->items_num) && (i < BATTLE_ITEM_MAX); ++i) {
        const struct battle_item_s *it = &bt->item[i];
        if ((((int)it->side == SIDE_L) || ((int)it->side == SIDE_R)) && (it->num > 0) && (s_battle_snap_n < BATTLE_ITEM_MAX)) {
            s_battle_snap[s_battle_snap_n].side = (uint8_t)it->side;
            s_battle_snap[s_battle_snap_n].look = (uint8_t)it->look;
            s_battle_snap[s_battle_snap_n].hull = (uint8_t)it->hull;
            s_battle_snap[s_battle_snap_n].num = (uint16_t)it->num;
            s_battle_snap_n++;
        }
    }
    s_battle_snap_bases = bt->bases;
    s_battle_snap_pside = (int)bt->planet_side;
    /* 1oom-mp: init EVERY human side's client IN PARALLEL (each runs the autoresolve
       prompt + sets up its battle UI at the same time). Battle goes interactive if any
       human picks Continue. Default AUTO outside MP. */
    if (g_mp_decision_hook_multi) {
        int players[2 * BATTLE_SIDE_PARTIES_MAX];
        battle_side_i_t sides[2 * BATTLE_SIDE_PARTIES_MAX];
        int n = mp_battle_human_owners(bt, players, sides); /* 1oom-mp: every human combatant (each side's lead + its allies) */
        if (n > 0) {
            uint8_t modes[2 * BATTLE_SIDE_PARTIES_MAX]; memset(modes, UI_BATTLE_AUTORESOLVE_AUTO, sizeof(modes)); /* default before the per-owner prompt fills each */
            if (g_mp_decision_hook_multi(players, n, MP_DEC_BATTLE_INIT, bt, (int)sizeof(*bt), modes, 1) == 0) {
                ui_battle_autoresolve_t result = UI_BATTLE_AUTORESOLVE_AUTO;
                bool side_fights[2] = { false, false };
                for (int i = 0; i < n; ++i) {
                    /* 1oom-mp teams: EACH owner's choice drives only its OWN ships. The battle goes
                       interactive if ANY owner picks Continue (OFF); an owner who picked Auto/Retreat is
                       never prompted (ui_battle_turn flees its ships) so the server can't deadlock on a
                       passive client. Retreat also sets that owner's ships fleeing immediately. */
                    s_battle_owner_mode[players[i]] = modes[i];
                    if (modes[i] == UI_BATTLE_AUTORESOLVE_OFF) {
                        result = UI_BATTLE_AUTORESOLVE_OFF;
                        side_fights[sides[i]] = true;
                    } else if (modes[i] == UI_BATTLE_AUTORESOLVE_RETREAT) {
                        for (int it = 1; (it <= (int)bt->items_num) && (it < BATTLE_ITEM_MAX); ++it) {
                            if (bt->item[it].owner == players[i]) { bt->item[it].retreat = 1; }
                        }
                    }
                }
                /* a human side with NO fighting owner is fully auto-handled (no per-ship prompts). */
                for (int side = SIDE_L; side <= SIDE_R; ++side) {
                    if (bt->s[side].flag_human && !side_fights[side]) { bt->s[side].flag_auto = 1; }
                }
                {
                    /* 1oom-mp diagnostic: the observer "press W to watch" offer is sent ONLY when the
                       fight goes interactive (result==OFF). An auto-resolved/retreated teammate battle
                       builds no live arena and streams no frames, so observers correctly get the combat
                       wait banner but NO watch prompt -- which looks like a bug. Log both the decision
                       and how many teammates were eligible so a "watch prompt never appeared" report is
                       conclusive: eligible>0 + interactive=no => auto-resolved (expected, nothing live);
                       eligible==0 => a team/filter problem (no one to offer). */
                    int eligible = mp_battle_observer_count(bt);
                    int sent = 0;
                    if (result == UI_BATTLE_AUTORESOLVE_OFF) {
                        /* the fight will be played live -> tell observing teammates to load the arena and
                           watch (reliable: must arrive before the frames it precedes). */
                        static uint8_t ibuf[1 + sizeof(struct battle_s)];
                        ibuf[0] = UI_MP_SPEC_BATTLE_INIT;
                        memcpy(ibuf + 1, bt, sizeof(struct battle_s));
                        sent = mp_spec_send_observers(bt, ibuf, 1 + (int)sizeof(struct battle_s), 1);
                    }
                    log_message("MP spectate: battle at planet %d leads L=%d R=%d interactive=%s watch-offer-eligible=%d offer-sent=%d\n",
                                (int)bt->planet_i, bt->s[SIDE_L].party, bt->s[SIDE_R].party,
                                (result == UI_BATTLE_AUTORESOLVE_OFF) ? "yes" : "no", eligible, sent);
                }
                return result;
            }
        }
    }
    return UI_BATTLE_AUTORESOLVE_AUTO;
}

void ui_battle_shutdown(struct battle_s *bt, bool colony_destroyed, int winner)
{
    /* 1oom-mp: tear down EVERY human side's battle UI -- must mirror ui_battle_init, which inits
       all human sides. If only one side were told to end (the old SIDE_L-or-SIDE_R pick), a human
       on the OTHER side of a human-vs-human battle would keep its battle context (s_mp_battle_uictx)
       set forever, and then re-render that stale battle on every later combat-wait broadcast --
       even while completely uninvolved in someone else's fight. */
    if (g_mp_decision_hook_multi) {
        int players[2 * BATTLE_SIDE_PARTIES_MAX];
        int n = mp_battle_human_owners(bt, players, NULL); /* 1oom-mp: tear down every human owner's battle UI */
        if (n > 0) {
            static uint8_t buf[sizeof(struct battle_s) + 8];
            int32_t w = winner; uint8_t resp[2 * BATTLE_SIDE_PARTIES_MAX] = { 0 }; /* 1oom-mp: one ack byte PER human owner (BATTLE_END returns 0, COMBAT_REPORT returns 1) -- size for the whole coalition like players[] above, not the old 2, else >=3 human owners overflow the stack */
            memcpy(buf, bt, sizeof(struct battle_s));
            buf[sizeof(struct battle_s)] = colony_destroyed ? 1 : 0;
            memcpy(buf + sizeof(struct battle_s) + 1, &w, 4);
            g_mp_decision_hook_multi(players, n, MP_DEC_BATTLE_END, buf, (int)sizeof(struct battle_s) + 5, resp, 1);
            /* 1oom-mp: tear down any OBSERVING teammate's arena too (reliable: else the finished battle
               keeps rendering on their screen forever). Prefix the same [battle_s][colony][winner] buf. */
            {
                static uint8_t ebuf[1 + sizeof(struct battle_s) + 8];
                ebuf[0] = UI_MP_SPEC_BATTLE_END;
                memcpy(ebuf + 1, buf, sizeof(struct battle_s) + 5);
                mp_spec_send_observers(bt, ebuf, 1 + (int)sizeof(struct battle_s) + 5, 1);
            }
            if (bt->autoresolve) {
                /* auto-resolved: send each involved human the per-design losses for both sides, for the
                   consolidated end-of-turn combat report (the per-battle result screen is suppressed). */
                struct ui_combat_report_s rep;
                memset(&rep, 0, sizeof(rep));
                rep.planet_i = (uint16_t)bt->planet_i;
                rep.winner_party = ((winner == SIDE_L) || (winner == SIDE_R)) ? (int16_t)bt->s[winner].party : -1;
                rep.party[0] = (uint8_t)bt->s[SIDE_L].party;
                rep.party[1] = (uint8_t)bt->s[SIDE_R].party;
                for (int k = 0; k < s_battle_snap_n; ++k) {
                    int side = s_battle_snap[k].side;
                    int before = (int)s_battle_snap[k].num;
                    int after = (int)mp_battle_item_num(bt, side, s_battle_snap[k].look, s_battle_snap[k].hull);
                    if ((before > 0) && (side >= 0) && (side < 2) && (rep.nitems[side] < NUM_SHIPDESIGNS)) {
                        rep.ships[side][rep.nitems[side]].look = s_battle_snap[k].look;
                        rep.ships[side][rep.nitems[side]].hull = s_battle_snap[k].hull;
                        rep.ships[side][rep.nitems[side]].before = (uint16_t)before;
                        rep.ships[side][rep.nitems[side]].after = (uint16_t)(after < 0 ? 0 : after);
                        rep.nitems[side]++;
                    }
                }
                if ((s_battle_snap_pside == SIDE_L) || (s_battle_snap_pside == SIDE_R)) {
                    rep.bases_before[s_battle_snap_pside] = s_battle_snap_bases;
                    rep.bases_after[s_battle_snap_pside] = (uint16_t)bt->bases;
                }
                g_mp_decision_hook_multi(players, n, MP_DEC_COMBAT_REPORT, &rep, (int)sizeof(rep), resp, 1);
            }
        }
    }
}

static void mp_spec_send(const struct battle_s *bt, uint8_t kind, const int *args, int nargs); /* fwd: defined below */

void ui_battle_draw_misshield(const struct battle_s *bt, int target_i, int target_x, int target_y, int missile_i)
{
}

void ui_battle_draw_damage(const struct battle_s *bt, int target_i, int target_x, int target_y, uint32_t damage)
{
    int a[5] = { target_i, target_x, target_y, (int)(damage & 0xffff), (int)((damage >> 16) & 0xffff) };
    mp_spec_send(bt, UI_MP_SPEC_DAMAGE, a, 5);
}

void ui_battle_draw_explos_small(const struct battle_s *bt, int x, int y)
{
}

void ui_battle_draw_basic(const struct battle_s *bt)
{
    /* 1oom-mp: stream the battle to any human NOT currently acting, so they can watch
       the fight progress instead of staring at a frozen frame. */
    if (g_mp_spectate_hook) {
        int actor = bt->item[bt->cur_item].owner; /* 1oom-mp: the owner currently being asked to move */
        /* stream the live frame to every OTHER human owner (combatant) + every observing teammate. */
        mp_spec_send_owners(bt, bt, (int)sizeof(*bt), 0/*best-effort: full snapshot self-heals*/, actor);
        mp_spec_send_observers(bt, bt, (int)sizeof(*bt), 0/*best-effort: full snapshot self-heals*/);
    }
}

void ui_battle_draw_basic_copy(const struct battle_s *bt)
{
}

void ui_battle_draw_missile(const struct battle_s *bt, int missilei, int x, int y, int tx, int ty)
{
    /* 1oom-mp: relay missile flight so spectators see the missile travel instead of teleporting (this
       was a no-op, hence "missiles just appear"). The client animator needs bt->missile[missilei]
       (wpnt/nummissiles/speed/target/fuel); a missile is launched mid-turn, after the spectator's last
       full snapshot, so ship the missile struct alongside the from/to coords. Display-only. */
    if (!g_mp_spectate_hook) { return; }
    if ((missilei < 0) || (missilei >= BATTLE_MISSILE_MAX)) { return; }
    {
        uint8_t b[1 + 10 + sizeof(struct battle_missile_s)];
        int p = 0;
        const int16_t vals[5] = { (int16_t)missilei, (int16_t)x, (int16_t)y, (int16_t)tx, (int16_t)ty };
        b[p++] = UI_MP_SPEC_MISSILE;
        for (int i = 0; i < 5; ++i) { b[p++] = (uint8_t)(vals[i] & 0xff); b[p++] = (uint8_t)((vals[i] >> 8) & 0xff); }
        memcpy(b + p, &bt->missile[missilei], sizeof(struct battle_missile_s));
        p += (int)sizeof(struct battle_missile_s);
        mp_spec_send_owners(bt, b, p, 1/*reliable: missile flight*/, -1);
        mp_spec_send_observers(bt, b, p, 1/*reliable: missile flight*/);
    }
}

void ui_battle_draw_cloaking(const struct battle_s *bt, int from, int to, int sx, int sy)
{
}

void ui_battle_draw_arena(const struct battle_s *bt, int itemi, int dmode)
{
}

void ui_battle_draw_item(const struct battle_s *bt, int itemi, int x, int y)
{
}

/* 1oom-mp: push a small battle animation event to the human(s) NOT currently acting (same audience
   as the draw_basic snapshot) so a spectator sees the attack play out. args are sent as int16. */
/* 1oom-mp: stream a battle event to teammates of either combatant who aren't themselves fighting,
   so they OBSERVE the fight live. NOT actor-gated -- an observer isn't acting, so it needs every
   frame. Each observer is sent at most once. */
static int mp_spec_send_observers(const struct battle_s *bt, const void *data, int len, int reliable)
{
    const struct game_s *g = bt->g;
    int pl, pr, sent = 0;
    if (!g_mp_spectate_hook || !g) { return 0; }
    pl = bt->s[SIDE_L].party; pr = bt->s[SIDE_R].party;
    for (int p = 0; p < g->players; ++p) {
        bool obs;
        if ((p == pl) || (p == pr) || !IS_HUMAN(g, p) || mp_battle_is_owner(bt, p)) { continue; } /* 1oom-mp: an ally OWNER is a combatant, not an observer */
        obs = ((pl >= 0) && (g->mp_team[pl] != 0) && (g->mp_team[p] == g->mp_team[pl]))
           || ((pr >= 0) && (g->mp_team[pr] != 0) && (g->mp_team[p] == g->mp_team[pr]));
        if (obs) { g_mp_spectate_hook(p, data, len, reliable); ++sent; }
    }
    return sent;
}

static void mp_spec_send(const struct battle_s *bt, uint8_t kind, const int *args, int nargs)
{
    if (!g_mp_spectate_hook) { return; }
    uint8_t b[1 + 2 * 8];
    if (nargs > 8) { nargs = 8; }
    b[0] = kind;
    for (int i = 0; i < nargs; ++i) { b[1 + i * 2] = (uint8_t)(args[i] & 0xff); b[2 + i * 2] = (uint8_t)((args[i] >> 8) & 0xff); }
    {
        /* send to EVERY human in the battle, including the one acting — they should see their own
           shot/retreat fire (the actor only gets state snapshots at its decision points otherwise). */
        mp_spec_send_owners(bt, b, 1 + nargs * 2, 1/*reliable: one-shot battle animation (beam/damage/retreat/...)*/, -1);
        mp_spec_send_observers(bt, b, 1 + nargs * 2, 1/*reliable: one-shot battle animation*/);
    }
}

void ui_battle_draw_bomb_attack(const struct battle_s *bt, int attacker_i, int target_i, ui_battle_bomb_t bombtype)
{
    int a[3] = { attacker_i, target_i, (int)bombtype };
    mp_spec_send(bt, UI_MP_SPEC_BOMB, a, 3);
}

void ui_battle_draw_beam_attack(const struct battle_s *bt, int attacker_i, int target_i, int wpni)
{
    int a[3] = { attacker_i, target_i, wpni };
    mp_spec_send(bt, UI_MP_SPEC_BEAM, a, 3);
}

void ui_battle_draw_stasis(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STASIS, a, 2);
}

void ui_battle_draw_pulsar(const struct battle_s *bt, int attacker_i, int ptype, const uint32_t *dmgtbl)
{
}

void ui_battle_draw_stream1(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STREAM1, a, 2);
}

void ui_battle_draw_stream2(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_STREAM2, a, 2);
}

void ui_battle_draw_blackhole(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_BLACKHOLE, a, 2);
}

void ui_battle_draw_technull(const struct battle_s *bt, int attacker_i, int target_i)
{
    int a[2] = { attacker_i, target_i };
    mp_spec_send(bt, UI_MP_SPEC_TECHNULL, a, 2);
}

void ui_battle_draw_repulse(const struct battle_s *bt, int attacker_i, int target_i, int sx, int sy)
{
    int a[4] = { attacker_i, target_i, sx, sy };
    mp_spec_send(bt, UI_MP_SPEC_REPULSE, a, 4);
}

void ui_battle_draw_retreat(const struct battle_s *bt)
{
    int a[1] = { bt->cur_item };
    mp_spec_send(bt, UI_MP_SPEC_RETREAT, a, 1);
}

void ui_battle_draw_bottom(const struct battle_s *bt)
{
}

void ui_battle_draw_planetinfo(const struct battle_s *bt, bool side_r)
{
}

void ui_battle_draw_scan(const struct battle_s *bt, bool side_r)
{
}

void ui_battle_draw_finish(const struct battle_s *bt)
{
}

void ui_battle_area_setup(const struct battle_s *bt)
{
}

void ui_battle_turn_pre(const struct battle_s *bt)
{
}

void ui_battle_turn_post(const struct battle_s *bt)
{
}

ui_battle_action_t ui_battle_turn(const struct battle_s *bt)
{
    /* 1oom-mp: ask the current ship's owner for one action (client runs the local
       poll loop and returns a real action; the server's per-frame loop becomes
       one RPC per action). Default AUTO. */
    if (g_mp_decision_hook) {
        int owner = bt->item[bt->cur_item].owner; /* 1oom-mp teams: ask the CURRENT SHIP'S owner, not the side lead */
        if ((owner >= 0) && (owner < PLAYER_NUM) && IS_HUMAN(bt->g, owner)) {
            if (s_battle_owner_mode[owner] == UI_BATTLE_AUTORESOLVE_OFF) {
                uint8_t act = UI_BATTLE_ACT_AUTO;
                int r = g_mp_decision_hook(owner, MP_DEC_BATTLE_TURN, bt, (int)sizeof(*bt), &act, 1);
                if (r >= 1) { return act; }
            } else {
                return UI_BATTLE_ACT_RETREAT; /* this owner chose auto/retreat -> its ships flee (v1: no per-ship AI) */
            }
        }
    }
    return UI_BATTLE_ACT_AUTO;
}

void ui_battle_ai_pre(const struct battle_s *bt)
{
}

bool ui_battle_ai_post(const struct battle_s *bt)
{
    return false;
}

int ui_spy_steal(struct game_s *g, int spy, int target, uint8_t flags_field)
{
    /* 1oom-mp: ask the spying human which tech field to steal (default 0 outside MP) */
    if (g_mp_decision_hook) {
        struct { int32_t spy, target; uint8_t flags; } rq;
        int32_t fld = 0;
        rq.spy = spy; rq.target = target; rq.flags = flags_field;
        int r = g_mp_decision_hook(spy, MP_DEC_SPY_STEAL, &rq, sizeof(rq), &fld, sizeof(fld));
        if (r >= (int)sizeof(fld)) { return fld; }
    }
    return 0;
}

void ui_spy_stolen(struct game_s *g, int pi, int spy, int field, uint8_t tech)
{
    /* 1oom-mp: tell the human victim which tech was stolen (self-contained; no game state needed) */
    if (g_mp_decision_hook && !IS_AI(g, pi)) {
        struct { int32_t spy, field; uint8_t tech; } rq;
        uint8_t ack = 0;
        memset(&rq, 0, sizeof(rq));
        rq.spy = spy; rq.field = field; rq.tech = tech;
        g_mp_decision_hook(pi, MP_DEC_SPY_STOLEN, &rq, (int)sizeof(rq), &ack, 1);
    }
}

ui_sabotage_t ui_spy_sabotage_ask(struct game_s *g, int spy, int target, planet_id_t *planetptr)
{
    /* 1oom-mp: ask the spying human what to sabotage + where (default none outside MP) */
    if (g_mp_decision_hook) {
        struct { int32_t spy, target; } rq;
        struct { int32_t act; uint16_t planet; } rs = { 0, PLANET_NONE };
        rq.spy = spy; rq.target = target;
        int r = g_mp_decision_hook(spy, MP_DEC_SPY_SABOTAGE, &rq, sizeof(rq), &rs, sizeof(rs));
        if (r >= (int)sizeof(rs)) {
            if (planetptr) { *planetptr = (planet_id_t)rs.planet; }
            return (ui_sabotage_t)rs.act;
        }
    }
    /* relay failed (e.g. the spying client dropped): do NOTHING, not a factory sabotage. 0 is
       UI_SABOTAGE_FACT; UI_SABOTAGE_NONE is -1. Returning 0 here made a dropped client trigger a
       bogus FACT sabotage on PLANET_NONE. */
    if (planetptr) { *planetptr = PLANET_NONE; }
    return UI_SABOTAGE_NONE;
}

int ui_spy_sabotage_done(struct game_s *g, int pi, int spy, int target, ui_sabotage_t act, int other1, int other2, planet_id_t planet, int snum)
{
    /* 1oom-mp: this BLOCKING result is for the saboteur ONLY, never the victim here -- the victim is
       notified via the non-blocking ui_spy_sabotage_show path instead (MP_DEC_SPY_RESULT_SHOW, buffered
       + replayed at their turn start). It can't be relayed here because the victim's screen
       (game_spy_sab_human's second loop) is a blocking popup on a passive player; relaying it deadlocks
       resolution waiting for a "continue" ack that can't come (it renders black), and it fires bogusly
       for an incited revolt. Discriminate by `target`: the saboteur views the TARGET empire's planet
       (pi != target), the victim views their OWN planet (pi == target). Do NOT key on `spy` -- in the
       victim call that argument is sabotage_spy (a caught-magnitude number, not a player id) and
       collides with real ids like player 0. The screen reads post-sabotage planet state the client
       doesn't have yet, so we ship a one-planet snapshot with the params. */
    if (g_mp_decision_hook && !IS_AI(g, pi) && (pi != target) && (planet < g->galaxy_stars)) {
        struct { int32_t spy, target, act, other1, other2, snum, planet; planet_t psnap; } rq;
        int32_t other = PLAYER_NONE;
        memset(&rq, 0, sizeof(rq));
        rq.spy = spy; rq.target = target; rq.act = (int32_t)act;
        rq.other1 = other1; rq.other2 = other2; rq.snum = snum; rq.planet = (int32_t)planet;
        rq.psnap = g->planet[planet];
        BOOLVEC_SET1(rq.psnap.within_srange, pi); /* force "in range" so the client shows the current (post-sabotage) numbers */
        int r = g_mp_decision_hook(pi, MP_DEC_SPY_RESULT, &rq, (int)sizeof(rq), &other, (int)sizeof(other));
        if (r >= (int)sizeof(other)) { return (int)other; }
    }
    return PLAYER_NONE;
}

void ui_spy_sabotage_show(struct game_s *g, int pi, int spy, int target, ui_sabotage_t act, int other1, int other2, planet_id_t planet, int snum)
{
    /* 1oom-mp: non-blocking buffered variant of ui_spy_sabotage_done. Used at the saboteur's result when
       no framing choice is needed (other2 == PLAYER_NONE), so the return value is irrelevant. The client
       buffers it + instant-acks and replays at state load (with the snapshot swapped in), so the
       saboteur's result screen never blocks the other player. Ships the post-sabotage planet snapshot
       exactly like the blocking version. */
    if (g_mp_decision_hook && !IS_AI(g, pi) && (planet < g->galaxy_stars)) {
        struct { int32_t spy, target, act, other1, other2, snum, planet; planet_t psnap; } rq;
        uint8_t ack = 0;
        memset(&rq, 0, sizeof(rq));
        rq.spy = spy; rq.target = target; rq.act = (int32_t)act;
        rq.other1 = other1; rq.other2 = other2; rq.snum = snum; rq.planet = (int32_t)planet;
        rq.psnap = g->planet[planet];
        BOOLVEC_SET1(rq.psnap.within_srange, pi); /* force "in range" so the client shows post-sabotage numbers */
        g_mp_decision_hook(pi, MP_DEC_SPY_RESULT_SHOW, &rq, (int)sizeof(rq), &ack, 1);
    }
}

void ui_newtech(struct game_s *g, int pi)
{
}

bool ui_explore(struct game_s *g, int pi, planet_id_t planet_i, bool by_scanner, bool flag_colony_ship)
{
    /* 1oom-mp: the server never auto-colonizes a human's colony ship — the ship waits
       in orbit and the human is asked on their own client at turn start (see
       ui_mp_colonize_incoming), which records a colonize order the server applies. */
    return false;
}

void ui_landing(struct game_s *g, int pi, planet_id_t planet_i)
{
}

bool ui_bomb_ask(struct game_s *g, int pi, planet_id_t planet_i, int pop_inbound)
{
    /* 1oom-mp: ask the attacking human's client whether to bomb (the server blocks
       on the answer). Default "no" outside MP (g_mp_decision_hook NULL). */
    if (g_mp_decision_hook) {
        uint8_t req[8], resp = 0;
        req[0] = (uint8_t)(pi >> 8);          req[1] = (uint8_t)pi;
        req[2] = (uint8_t)(planet_i >> 8);    req[3] = (uint8_t)planet_i;
        req[4] = (uint8_t)(pop_inbound >> 24); req[5] = (uint8_t)(pop_inbound >> 16);
        req[6] = (uint8_t)(pop_inbound >> 8);  req[7] = (uint8_t)pop_inbound;
        int r = g_mp_decision_hook(pi, MP_DEC_BOMB, req, 8, &resp, 1);
        return (r >= 1) && (resp != 0);
    }
    return false;
}

void ui_bomb_show(struct game_s *g, int pi, int attacker_i, int owner_i, planet_id_t planet_i, int popdmg, int factdmg, bool play_music, bool hide_other)
{
    /* 1oom-mp: the server resolves the bombing on this null UI, so relay the result (pop killed /
       factories destroyed) to the human attacker AND the human owner, who each render it. */
    (void)pi;
    if (g_mp_decision_hook_multi) {
        int players[2], n = 0;
        int cand[2]; cand[0] = attacker_i; cand[1] = owner_i;
        for (int k = 0; k < 2; ++k) {
            int p = cand[k];
            if ((p < 0) || (p >= (int)g->players) || !IS_HUMAN(g, p)) { continue; }
            bool dup = false;
            for (int j = 0; j < n; ++j) { if (players[j] == p) { dup = true; break; } }
            if (!dup) { players[n++] = p; }
        }
        if ((n > 0) && (planet_i < g->galaxy_stars)) {
            /* ship the params + a snapshot of the bombed planet: ui_bomb_show reads the planet's live
               owner, which can flip to NONE when a bombing depopulates it, so the client patches this
               in to render correctly at replay-time regardless of later same-turn changes. */
            struct { int32_t attacker, owner, planet, popdmg, factdmg; uint8_t play_music, hide_other; planet_t psnap; } req;
            uint8_t resp[2] = {0, 0};
            memset(&req, 0, sizeof(req));
            req.attacker = attacker_i; req.owner = owner_i; req.planet = (int32_t)planet_i;
            req.popdmg = popdmg; req.factdmg = factdmg;
            req.play_music = play_music ? 1 : 0; req.hide_other = hide_other ? 1 : 0;
            req.psnap = g->planet[planet_i];
            g_mp_decision_hook_multi(players, n, MP_DEC_BOMB_SHOW, &req, (int)sizeof(req), resp, 1);
        }
    }
}

bool ui_bomb_ask_batch(struct game_s *g, const struct ui_bomb_target_s *targets, int n, bool *decided)
{
    /* 1oom-mp: fan the whole turn's target list out to every human attacker AT ONCE (parallel) so both
       players decide their bombings simultaneously rather than one-at-a-time. Each client prompts for
       ITS own targets and returns a u64 yes/no bitmask (bit k = bomb targets[k]); demux per attacker. */
    if ((!g_mp_decision_hook_multi) || (n <= 0)) { return false; }
    if (n > 64) { n = 64; }
    {
        int players[8], np = 0;
        for (int k = 0; k < n; ++k) {
            int a = targets[k].attacker;
            bool dup = false;
            if ((a < 0) || (a >= (int)g->players) || (!IS_HUMAN(g, a))) { continue; }
            for (int j = 0; j < np; ++j) { if (players[j] == a) { dup = true; break; } }
            if ((!dup) && (np < 8)) { players[np++] = a; }
        }
        if (np == 0) { return false; }
        {
            static uint8_t req[4 + 64 * sizeof(struct ui_bomb_target_s)];
            uint8_t resp[8 * 8];
            int32_t n32 = n;
            memset(resp, 0, sizeof(resp));
            memcpy(req, &n32, 4);
            memcpy(req + 4, targets, (size_t)n * sizeof(struct ui_bomb_target_s));
            g_mp_decision_hook_multi(players, np, MP_DEC_BOMB_BATCH, req, 4 + n * (int)sizeof(struct ui_bomb_target_s), resp, 8);
            for (int k = 0; k < n; ++k) {
                int a = targets[k].attacker, pidx = -1;
                uint64_t mask = 0;
                for (int j = 0; j < np; ++j) { if (players[j] == a) { pidx = j; break; } }
                if (pidx >= 0) { memcpy(&mask, resp + pidx * 8, 8); }
                decided[k] = (((mask >> k) & 1) != 0);
            }
        }
    }
    return true;
}

bool ui_spy_sabotage_batch(struct game_s *g, const struct ui_spy_sab_target_s *targets, int n, struct ui_spy_sab_dec_s *out)
{
    /* 1oom-mp: fan the whole turn's sabotage-opportunity list out to every human spymaster AT ONCE
       (parallel) so both players pick their sabotage simultaneously rather than one-at-a-time. Each
       client answers for ITS own opportunities (act+planet) and returns a ui_spy_sab_dec_s[n] array;
       demux opportunity k from its saboteur-player's slot. Mirrors ui_bomb_ask_batch. */
    if ((!g_mp_decision_hook_multi) || (n <= 0)) { return false; }
    if (n > 32) { n = 32; }
    {
        int players[8], np = 0;
        for (int k = 0; k < n; ++k) {
            int a = targets[k].player;
            bool dup = false;
            if ((a < 0) || (a >= (int)g->players) || (!IS_HUMAN(g, a))) { continue; }
            for (int j = 0; j < np; ++j) { if (players[j] == a) { dup = true; break; } }
            if ((!dup) && (np < 8)) { players[np++] = a; }
        }
        if (np == 0) { return false; }
        {
            static uint8_t req[4 + 32 * sizeof(struct ui_spy_sab_target_s)];
            static uint8_t resp[8 * 32 * sizeof(struct ui_spy_sab_dec_s)];
            int32_t n32 = n;
            int rlen = n * (int)sizeof(struct ui_spy_sab_dec_s);
            memset(resp, 0, sizeof(resp));
            memcpy(req, &n32, 4);
            memcpy(req + 4, targets, (size_t)n * sizeof(struct ui_spy_sab_target_s));
            int rc = g_mp_decision_hook_multi(players, np, MP_DEC_SPY_SABOTAGE_BATCH, req, 4 + n * (int)sizeof(struct ui_spy_sab_target_s), resp, rlen);
            for (int k = 0; k < n; ++k) {
                int a = targets[k].player, pidx = -1;
                /* safe default: a dropped client leaves its slot at the memset 0, which would decode to
                   act=0 (UI_SABOTAGE_FACT) on planet 0 -- a real factory sabotage. Default to NONE and
                   only trust the slots when the whole batch succeeded (rc == 0 => every player answered). */
                out[k].act = -1; out[k].planet = PLANET_NONE;
                if (rc != 0) { continue; }
                for (int j = 0; j < np; ++j) { if (players[j] == a) { pidx = j; break; } }
                if (pidx >= 0) {
                    memcpy(&out[k], resp + pidx * rlen + k * (int)sizeof(struct ui_spy_sab_dec_s), sizeof(struct ui_spy_sab_dec_s));
                }
            }
        }
    }
    return true;
}

bool ui_spy_steal_batch(struct game_s *g, const struct ui_spy_steal_target_s *targets, int n, int16_t *out)
{
    /* 1oom-mp: fan the whole turn's steal-opportunity list out to every human spy AT ONCE (parallel)
       so both players pick which tech to steal simultaneously rather than one-at-a-time. Each client
       answers for ITS own opportunities (chosen field) and returns an int16_t[n] array; demux
       opportunity k from its spy-player's slot. Mirrors ui_spy_sabotage_batch. */
    if ((!g_mp_decision_hook_multi) || (n <= 0)) { return false; }
    if (n > 32) { n = 32; }
    {
        int players[8], np = 0;
        for (int k = 0; k < n; ++k) {
            int a = targets[k].spy;
            bool dup = false;
            if ((a < 0) || (a >= (int)g->players) || (!IS_HUMAN(g, a))) { continue; }
            for (int j = 0; j < np; ++j) { if (players[j] == a) { dup = true; break; } }
            if ((!dup) && (np < 8)) { players[np++] = a; }
        }
        if (np == 0) { return false; }
        {
            static uint8_t req[4 + 32 * sizeof(struct ui_spy_steal_target_s)];
            static int16_t resp[8 * 32];
            int32_t n32 = n;
            int rlen = n * (int)sizeof(int16_t);
            memset(resp, 0, sizeof(resp));
            memcpy(req, &n32, 4);
            memcpy(req + 4, targets, (size_t)n * sizeof(struct ui_spy_steal_target_s));
            int rc = g_mp_decision_hook_multi(players, np, MP_DEC_SPY_STEAL_BATCH, req, 4 + n * (int)sizeof(struct ui_spy_steal_target_s), (uint8_t *)resp, rlen);
            for (int k = 0; k < n; ++k) {
                int a = targets[k].spy, pidx = -1;
                /* -1 = steal nothing. A dropped client leaves its slot at 0 (= field 0, a real steal);
                   only trust the slots when the whole batch succeeded (rc == 0 => every player answered). */
                if (rc != 0) { out[k] = -1; continue; }
                for (int j = 0; j < np; ++j) { if (players[j] == a) { pidx = j; break; } }
                out[k] = (pidx >= 0) ? resp[pidx * n + k] : -1;
            }
        }
    }
    return true;
}

void ui_turn_pre(const struct game_s *g)
{
}

void ui_turn_msg(struct game_s *g, int pi, const char *str)
{
}

void ui_ground(struct game_s *g, struct ground_s *gr)
{
    /* 1oom-mp: the server resolves the invasion on this null UI, so relay the result + animation to
       the human attacker AND the human defender so both watch it (ground_s is pointer-free). */
    if (g_mp_decision_hook_multi) {
        int players[2], n = 0;
        for (int side = 0; side < 2; ++side) {
            int p = gr->s[side].player;
            if ((p < 0) || (p >= (int)g->players) || !IS_HUMAN(g, p)) { continue; }
            bool dup = false;
            for (int j = 0; j < n; ++j) { if (players[j] == p) { dup = true; break; } }
            if (!dup) { players[n++] = p; }
        }
        if (n > 0) {
            uint8_t resp[2] = {0, 0};
            g_mp_decision_hook_multi(players, n, MP_DEC_GROUND, gr, (int)sizeof(*gr), resp, 1);
        }
    }
}

void ui_news_start(void)
{
}

/* 1oom-mp: news the whole galaxy would plausibly know (space monsters, an empire wiped out, the
   end-of-turn standings) -- shown to every human. Everything else is personal and goes only to the
   empire it happened to. Keeps enemy internal troubles private and the "your colony" phrasing right. */
static bool mp_news_is_global(int type)
{
    switch (type) {
        case GAME_NEWS_STATS:
        case GAME_NEWS_GENOCIDE:
        case GAME_NEWS_AMOEBA:
        case GAME_NEWS_CRYSTAL:
        case GAME_NEWS_GUARDIAN:
        case GAME_NEWS_ORION:
        case GAME_NEWS_PIRATES:
        case GAME_NEWS_COMET:
        case GAME_NEWS_NOVA:
        case GAME_NEWS_STARS:
            return true;
        default:
            return false;
    }
}

void ui_news(struct game_s *g, struct news_s *ns)
{
    /* the turn resolves headless here, so relay each report to the humans it concerns. They buffer
       the records and replay the GNN broadcast when the new turn's state loads (see game.c). */
    if (!g_mp_decision_hook) { return; }
    {
        struct { int32_t type, subtype, num1, num2, race, planet_i; } rq;
        bool global = mp_news_is_global((int)ns->type);
        player_id_t owner = PLAYER_NONE;
        rq.type = (int32_t)ns->type; rq.subtype = (int32_t)ns->subtype;
        rq.num1 = (int32_t)ns->num1; rq.num2 = (int32_t)ns->num2;
        rq.race = (int32_t)ns->race; rq.planet_i = (int32_t)ns->planet_i;
        if ((!global) && (ns->planet_i < g->galaxy_stars)) { owner = g->planet[ns->planet_i].owner; }
        /* 1oom-mp: the computer-virus report hits an empire's research, not one of its colonies, so it
           carries no planet_i -- the lookup above misses, owner stays NONE, and it would broadcast to the
           whole galaxy. Route it to the single empire it concerns, found by race (each empire is a
           distinct race). If virus_player is an AI, no human matches and no human is told -- correct. */
        if ((!global) && (ns->type == GAME_NEWS_VIRUS) && (ns->race < RACE_NUM)) {
            owner = PLAYER_NONE;
            for (player_id_t pe = PLAYER_0; pe < g->players; ++pe) {
                if (g->eto[pe].race == (race_t)ns->race) { owner = pe; break; }
            }
        }
        for (player_id_t pi = PLAYER_0; pi < g->players; ++pi) {
            if (IS_AI(g, pi)) { continue; }
            if (global || (owner == pi) || (owner == PLAYER_NONE)) {
                uint8_t ack = 0;
                g_mp_decision_hook(pi, MP_DEC_NEWS_ITEM, &rq, (int)sizeof(rq), &ack, 1);
            }
        }
    }
}

void ui_news_end(void)
{
}

void ui_combat_report(struct game_s *g, int pi, const struct ui_combat_report_s *reps, int n)
{
    (void)g; (void)pi; (void)reps; (void)n; /* headless server never renders the report */
}

/* 1oom-mp: the council is a plenary event (every empire is present), so stream the chamber state to
   ALL human players via the spectate channel -- they render it while waiting (shared synchronous
   view). The vote/accept stay per-human (decision RPC). Pointers are zeroed for transport. */
static void mp_election_relay(struct election_s *el, int kind)
{
    if (!g_mp_spectate_hook || !el || !el->g) { return; }
    uint8_t buf[1 + sizeof(struct election_s) + 256];
    int len = 1;
    buf[0] = (uint8_t)kind;
    if (kind == UI_MP_SPEC_COUNCIL) {
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        memcpy(buf + 1, &e, sizeof(e));
        len = 1 + (int)sizeof(e);
        /* 1oom-mp: el->str (the chamber announcement / vote tally / "X is now emperor" / "no
           majority" result banner) is a pointer into server memory, so the zeroed copy above leaves
           the client with nothing to draw -- no council text ever shows. Append the TEXT so the
           client can re-point el->str at its own copy (see mp_if_on_spectate). */
        {
            const char *s = el->str ? el->str : "";
            int slen = (int)strlen(s);
            if (slen > 255) { slen = 255; }
            memcpy(buf + len, s, (size_t)slen);
            buf[len + slen] = 0;
            len += slen + 1;
        }
    }
    for (player_id_t p = PLAYER_0; p < el->g->players; ++p) {
        if (IS_HUMAN(el->g, p)) { g_mp_spectate_hook(p, buf, len, 0/*best-effort: council frame is full state, self-heals*/); }
    }
}

void ui_election_start(struct election_s *el)
{
    mp_election_relay(el, UI_MP_SPEC_COUNCIL);
}

void ui_election_show(struct election_s *el)
{
    mp_election_relay(el, UI_MP_SPEC_COUNCIL);
    /* the council runs headless here with no pacing, so spectators would only ever see the latest
       frame before the next one / the tear-down. Hold each step so they can actually read it. */
    if (g_mp_spectate_hook) { usleep(900000); }
}

void ui_election_delay(struct election_s *el, int delay)
{
    if (g_mp_spectate_hook && (delay > 0)) { usleep((useconds_t)delay * 120000); }
}

/* 1oom-mp: the galactic-council vote + accept happen during resolution; ship the
   election state to the voting human's client and ask there (the struct's pointers
   are zeroed for transport and re-pointed client-side). Default outside MP unchanged. */
int ui_election_vote(struct election_s *el, int player_i)
{
    if (g_mp_decision_hook) {
        /* 1oom-mp: the vote is a private RPC, so the shared chamber would otherwise freeze on the last
           narration while this human decides -- spectators can't tell who they're waiting on. Stream a
           clear "Awaiting <Empire>..." frame to everyone first (cur_i already marks the voter). */
        if (g_mp_spectate_hook && el->g) {
            char wbuf[80];
            const char *saved = el->str;
            lib_sprintf(wbuf, sizeof(wbuf), "Awaiting the vote of %s...", el->g->emperor_names[player_i]);
            el->str = wbuf;
            mp_election_relay(el, UI_MP_SPEC_COUNCIL);
            el->str = saved;
        }
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        uint8_t req[sizeof(struct election_s) + 4];
        int32_t pi32 = player_i, vote = 0;
        memcpy(req, &e, sizeof(e));
        memcpy(req + sizeof(e), &pi32, 4);
        int r = g_mp_decision_hook(player_i, MP_DEC_ELECTION_VOTE, req, (int)sizeof(req), &vote, sizeof(vote));
        if (r >= (int)sizeof(vote)) { return vote; }
    }
    return 0;
}

bool ui_election_accept(struct election_s *el, int player_i)
{
    if (g_mp_decision_hook) {
        struct election_s e = *el;
        e.g = NULL; e.uictx = NULL; e.buf = NULL; e.str = NULL;
        uint8_t req[sizeof(struct election_s) + 4], resp = 0;
        int32_t pi32 = player_i;
        memcpy(req, &e, sizeof(e));
        memcpy(req + sizeof(e), &pi32, 4);
        int r = g_mp_decision_hook(player_i, MP_DEC_ELECTION_ACCEPT, req, (int)sizeof(req), &resp, 1);
        if (r >= 1) { return resp != 0; }
    }
    return false;
}

void ui_election_end(struct election_s *el)
{
    /* hold the final result on every spectator's screen before tearing the council down, otherwise
       the next turn's state load wipes it instantly and players never see who won. */
    if (g_mp_spectate_hook) { sleep(3); }
    mp_election_relay(el, UI_MP_SPEC_COUNCIL_END);
}

void ui_election_ctx_load(struct election_s *el)
{
}

void ui_election_ctx_free(struct election_s *el)
{
}

void ui_election_spectate(struct election_s *el)
{
}

/* 1oom-mp: the AI's diplomacy with a human runs through game_audience on this headless server;
   relay each ui_audience_* call to the human's client (au->ph) so they actually see the audience
   and answer. If au->ph isn't a connected human, the decision hook returns <0 and we fall back to
   the old auto-resolve default (0). Strings are sent as text since they may point at static
   game-string tables or the inline diplo_msg/strtbl_buf. */
static int16_t mp_audience_relay(uint8_t subtype, uint8_t ntpi, struct audience_s *au)
{
    if (!g_mp_decision_hook) { return 0; }
    static uint8_t req[8192];
    int pos = 0;
    req[pos++] = subtype;
    req[pos++] = ntpi;
    memcpy(req + pos, au, sizeof(*au)); pos += (int)sizeof(*au);
    uint16_t blen = au->buf ? (uint16_t)strlen(au->buf) : 0;
    if (blen > AUDIENCE_DIPLO_MSG_SIZE) { blen = AUDIENCE_DIPLO_MSG_SIZE; }
    memcpy(req + pos, &blen, 2); pos += 2;
    if (blen) { memcpy(req + pos, au->buf, blen); pos += blen; }
    uint8_t nstr = 0;
    while ((nstr < AUDIENCE_STR_MAX) && au->strtbl[nstr]) { ++nstr; }
    req[pos++] = nstr;
    for (int i = 0; i < nstr; ++i) {
        uint16_t l = (uint16_t)strlen(au->strtbl[i]);
        if (l > 255) { l = 255; }
        memcpy(req + pos, &l, 2); pos += 2;
        memcpy(req + pos, au->strtbl[i], l); pos += l;
    }
    req[pos++] = au->condtbl ? 1 : 0;
    if (au->condtbl) { for (int i = 0; i < nstr; ++i) { req[pos++] = au->condtbl[i] ? 1 : 0; } }
    uint8_t rsp[4];
    int r = g_mp_decision_hook(au->ph, MP_DEC_AUDIENCE, req, pos, rsp, (int)sizeof(rsp));
    if (r >= 2) { int16_t v; memcpy(&v, rsp, 2); return v; }
    return 0;
}

void ui_audience_start(struct audience_s *au) { mp_audience_relay(MP_AUD_START, 0, au); }
void ui_audience_show1(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW1, 0, au); }
void ui_audience_show2(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW2, 0, au); }
void ui_audience_show3(struct audience_s *au) { mp_audience_relay(MP_AUD_SHOW3, 0, au); }
int16_t ui_audience_ask2a(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK2A, 0, au); }
int16_t ui_audience_ask2b(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK2B, 0, au); }
int16_t ui_audience_ask3(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK3, 0, au); }
int16_t ui_audience_ask4(struct audience_s *au) { return mp_audience_relay(MP_AUD_ASK4, 0, au); }
void ui_audience_newtech(struct audience_s *au, int pi) { mp_audience_relay(MP_AUD_NEWTECH, (uint8_t)pi, au); }
void ui_audience_end(struct audience_s *au) { mp_audience_relay(MP_AUD_END, 0, au); }

void ui_newships(struct game_s *g, int pi)
{
}

void ui_copyprotection_check(struct game_s *g)
{
}

void ui_copyprotection_lose(struct game_s *g, struct game_end_s *ge)
{
}

void ui_mp_wait(int reason)
{
    (void)reason; /* headless server: never called (server side doesn't wait on a UI) */
}

void ui_mp_battle_spectate(const struct battle_s *bt)
{
    (void)bt; /* headless: client-only */
}

void ui_mp_battle_glide(struct battle_s *bt, int itemi, int sx, int sy)
{
    (void)bt; (void)itemi; (void)sx; (void)sy; /* headless: client-only */
}

void ui_battle_init_spectate(struct battle_s *bt)
{
    (void)bt; /* headless: the server never renders/observes */
}

int ui_mp_battle_watch_prompt(void)
{
    return 0; /* headless: never watches */
}

int ui_mp_lobby_run(int my_id)
{
    (void)my_id;
    return 0; /* headless server: never runs a client lobby (uses setup_game directly) */
}

